In [1]:
import numpy as np

In [4]:
random_array = np.random.randint(10,size=(4,4))
random_array

array([[0, 7, 4, 8],
       [1, 5, 2, 9],
       [7, 5, 1, 0],
       [4, 6, 1, 4]])

In [6]:
random_array

array([[0, 7, 4, 8],
       [1, 5, 2, 9],
       [7, 5, 1, 0],
       [4, 6, 1, 4]])

In [8]:
np.argmax(random_array
,axis=0)

array([2, 0, 0, 1], dtype=int64)

In [9]:
np.argmax(random_array,axis=1)

array([3, 3, 0, 1], dtype=int64)

In [11]:
r1= random_array[:,:-1]

In [12]:
r1

array([[0, 7, 4],
       [1, 5, 2],
       [7, 5, 1],
       [4, 6, 1]])

In [13]:
np.argmax(r1,axis=0)

array([2, 0, 0], dtype=int64)

In [14]:
np.argmax(r1,axis=1)

array([1, 1, 0, 1], dtype=int64)

In [15]:
np.max(r1,axis=0)

array([7, 7, 4])

In [16]:
np.max(r1,axis=1)

array([7, 5, 7, 6])

In [17]:
np.array([1,2,4])

array([1, 2, 4])

In [1]:
import numpy as np

In [8]:
a = np.array([
    [5,9,1],
    [2,8,7],
    [5,15,2]
])

In [9]:
a

array([[ 5,  9,  1],
       [ 2,  8,  7],
       [ 5, 15,  2]])

In [12]:
np.argmax(a,axis=1)

array([1, 1, 1], dtype=int64)

In [14]:
np.sum(a,axis=0)

array([12, 32, 10])